In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [15]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [17]:
X_train

    age  gender  fever   cough       city
29   34  Female    NaN  Strong     Mumbai
48   66    Male   99.0  Strong  Bangalore
0    60    Male  103.0    Mild    Kolkata
13   64    Male  102.0    Mild  Bangalore
2    42    Male  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
66   51    Male  104.0    Mild    Kolkata
96   51  Female  101.0  Strong    Kolkata
14   51    Male  104.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata
61   81  Female   98.0  Strong     Mumbai

[80 rows x 5 columns]

## 1. Aam Zindagi

In [18]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [19]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [21]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']]).toarray()

# also the test data
X_test_gender_city = ohe.transform(X_test[['gender','city']]).toarray()

X_train_gender_city.shape

(80, 4)

In [23]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[34],
       [66],
       [60],
       [64],
       [42],
       [19],
       [71],
       [44],
       [72],
       [65],
       [11],
       [34],
       [42],
       [14],
       [82],
       [13],
       [ 5],
       [69],
       [49],
       [80],
       [34],
       [75],
       [65],
       [19],
       [14],
       [75],
       [47],
       [82],
       [70],
       [68],
       [33],
       [20],
       [12],
       [56],
       [55],
       [69],
       [24],
       [83],
       [50],
       [60],
       [16],
       [81],
       [42],
       [65],
       [15],
       [49],
       [69],
       [49],
       [38],
       [59],
       [64],
       [47],
       [38],
       [22],
       [16],
       [19],
       [27],
       [24],
       [73],
       [20],
       [74],
       [31],
       [19],
       [ 8],
       [18],
       [82],
       [46],
       [10],
       [73],
       [26],
       [ 5],
       [17],
       [79],
       [20],
       [80],
       [51],
       [51],
       [51],
       [71],
       [81]])

In [25]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed

array([[ 34.        , 100.97222222,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 66.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 60.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 64.        , 102.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 71.        , 100.97222222,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 44.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 72.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 11.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 34.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 42.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 14.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 13.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [  5.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 69.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 80.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 75.        , 100.97222222,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,  99.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 14.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 47.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 82.        , 100.97222222,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 70.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 68.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 33.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 20.        , 100.97222222,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 12.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 55.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 24.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 83.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 50.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 60.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 16.        , 103.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 42.        , 100.97222222,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 65.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 15.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 49.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 49.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 38.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 59.        ,  99.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 64.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 47.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 38.        , 100.97222222,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 16.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 73.        , 103.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 20.        , 102.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 74.        , 102.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  8.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 18.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 46.        , 103.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 10.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 73.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 26.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [  5.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 17.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 79.        , 100.97222222,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 80.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 51.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 81.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ]])

In [29]:
import numpy as np
from sklearn.impute import SimpleImputer

# Imagine a dataset with a missing value (np.nan)
data = [[1, 2], 
        [np.nan, 3], 
        [7, 6]]

# Create the imputer, telling it to use the 'mean' strategy
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

# Fit the imputer to the data and transform it
clean_data = imputer.fit_transform(data)
clean_data

array([[1., 2.],
       [1., 3.],
       [7., 6.]])

## Mentos Zindagi

In [30]:
from sklearn.compose import ColumnTransformer

In [95]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [97]:
transformer.fit_transform(X_train).shape

(80, 7)

In [99]:
transformer.transform(X_test).shape

(20, 7)